service: lambda
provider:
  name: aws
  stage: dev
  runtime: python3.6
  region: us-east-2
  credentials:
    accessKeyId: AKIAUGSPO4IXAXAMBXGB
    secretAccessKey: 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 

functions:
  test_function:
    handler: handler.test_function
    memorySize: 512
    timeout: 60
    events:
      - http:
          path: get-hello
          method: get
          request:
            parameters:
              queryStrings:
                name: true


plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    dockerizePip: true
    slim: true
